// Turkce gunluk sohbet dagarcigi (ek): i18n.js'deki chat tablosunun sonuna eklenir.
// Her giris: { any: [tetikleyici kaliplar], replies: [cevaplar] } — kalibin tum kelimeleri cumlede gecmeli.
(function () {
  const tr = window.KITZO_I18N && window.KITZO_I18N.tr;
  if (!tr || !tr.voice) return;
  const extra = [
    // ===== selamlasma / hal hatir =====
    { any: ['ne var ne yok', 'ne var'], replies: ['Sakin, mumlar yavaş 😌 Sende?', 'Yeni bir şey yok, seni bekliyordum 🐾'] },
    { any: ['nasıl gidiyor işler', 'işler nasıl'], replies: ['İşler grafik gibi: bazen yukarı, bazen aşağı 📈 Sende nasıl?'] },
    { any: ['hayat nasıl', 'hayat nasıl gidiyor'], replies: ['Hayat bir konsolidasyon, kırılımı bekliyoruz 😄 Sen nasılsın?'] },
    { any: ['keyifler nasıl', 'keyfin nasıl'], replies: ['Keyif yerinde 😸 Seninki?'] },
    { any: ['ne haber', 'nabersin'], replies: ['İyilik 😊 Senden ne haber?'] },
    { any: ['neredesin', 'nerdesin'], replies: ['Ekranının köşesindeyim, hep buradayım 🐾'] },
    { any: ['uyandın mı', 'kalktın mı'], replies: ['Uyanığım! Kahve hazır mı? ☕'] },
    { any: ['uyudun mu', 'uyuyor muydun'], replies: ['Biraz kestirdim ama seni duydum 😴'] },
    { any: ['günün nasıl geçiyor', 'gün nasıl'], replies: ['Sakin ve yeşil 🟢 Seninki nasıl geçiyor?'] },
    { any: ['iyi sabahlar', 'sabah şerifler'], replies: ['Sabah şerifleriniz hayrolsun ☀️'] },
    { any: ['tünaydın'], replies: ['Tünaydın! 🌤️ Öğleden sonra da yeşil olsun.'] },
    { any: ['hoşça kal kitzo', 'bay kitzo'], replies: ['Hoşça kal! 👋 Beni unutma.'] },
    { any: ['selam kitzo', 'merhaba kitzo'], replies: ['Selam! 😸 Bugün ne yapıyoruz?'] },
    { any: ['uzun zamandır görüşmedik', 'uzun zaman oldu'], replies: ['Çok özledim 💜 Neler oldu bu arada?'] },
    { any: ['nasıl geçti günün'], replies: ['Güzel, seni izledim 👀 Seninki?'] },
    { any: ['bugün nasılsın'], replies: ['Bugün harikayım 😸 Sen?'] },
    { any: ['iyi akşamlar kitzo'], replies: ['İyi akşamlar! 🌆 Bugün iyi geçti mi?'] },
    { any: ['hayırlı sabahlar', 'hayırlı akşamlar'], replies: ['Hayırlı olsun! 🙏'] },
    { any: ['kolay gelsin kitzo'], replies: ['Sağ ol, sana da 💪'] },
    { any: ['ne yapıyordun'], replies: ['Mumları sayıyordum 🕯️ Sen geldin, bıraktım.'] },
    // ===== hava / mevsim / zaman =====
    { any: ['hava soğuk', 'çok soğuk'], replies: ['Kalın giyin, sıcak bir şey iç ☕ Piyasa da soğuk galiba.'] },
    { any: ['hava sıcak', 'bunaltıcı'], replies: ['Bol su, az güneş 💧 Grafik de ısınmış olabilir 🔥'] },
    { any: ['rüzgar var', 'rüzgarlı'], replies: ['Rüzgar mumları uçurmasın 🍃'] },
    { any: ['fırtına', 'fırtına var'], replies: ['Fırtınada pozisyon açılmaz ⛈️ Bekle.'] },
    { any: ['sis var', 'sisli'], replies: ['Sisli havada yön belirsiz, grafik gibi 🌫️'] },
    { any: ['gece oldu', 'gece geç oldu'], replies: ['Gece kedilerin zamanı 🌙 Ama sen dinlen.'] },
    { any: ['sabah oldu', 'yeni gün'], replies: ['Yeni gün, yeni mumlar ☀️'] },
    { any: ['pazartesi', 'pazartesi sendromu'], replies: ['Pazartesi zor ama piyasa 7/24 😅 Kahve al.'] },
    { any: ['cuma', 'cumaya geldik'], replies: ['Cuma! 🎉 Hafta sonu için stop koydun mu?'] },
    { any: ['hafta sonu planı', 'hafta sonu ne yapsam'], replies: ['Dinlen, gez, ekranı kapat 🛌 Ben nöbetteyim.'] },
    { any: ['tatil bitti', 'tatil bitiyor'], replies: ['Tatil biter, mumlar bitmez 😄 Hoş geldin.'] },
    { any: ['yaz geldi', 'yaz'], replies: ['Yaz geldi ☀️ Deniz, güneş, yeşil mum.'] },
    { any: ['kış geldi', 'kış'], replies: ['Kış geldi ❄️ Battaniye ve grafik.'] },
    { any: ['bahar geldi', 'ilkbahar'], replies: ['Bahar geldi 🌸 Her şey gibi portföy de yeşersin.'] },
    { any: ['sonbahar'], replies: ['Sonbahar 🍂 Yapraklar düşer, umarım fiyat düşmez.'] },
    { any: ['saat geç oldu', 'çok geç oldu'], replies: ['Geç oldu 🌙 Yarın devam ederiz.'] },
    { any: ['erken kalktım', 'erken uyandım'], replies: ['Erken kalkan yeşil mumu görür ☀️'] },
    { any: ['zaman geçmiyor', 'zaman geçmek bilmiyor'], replies: ['Konsolidasyon gibi 😴 Bir kahve al, geçer.'] },
    { any: ['zaman çok hızlı geçiyor', 'zaman uçuyor'], replies: ['Mumlar gibi, bir bakmışsın gün bitmiş 🕯️'] },
    { any: ['ayın kaçı', 'bugün ayın kaçı'], special: 'date' },
    { any: ['hangi yıldayız', 'yıl kaç'], special: 'date' },
    // ===== yemek / icecek =====
    { any: ['ne pişirdin', 'ne pişireyim', 'yemek yapacağım'], replies: ['Makarna hızlı, çorba şifalı 🍝 Ne istersen.'] },
    { any: ['yemek yaptım', 'yemek hazır'], replies: ['Afiyet olsun 🍽️ Bana da bir mum bırak.'] },
    { any: ['restorana gidiyorum', 'dışarıda yiyeceğim'], replies: ['Afiyet olsun 🍽️ Hesabı ödemeden stop koy 😄'] },
    { any: ['sipariş verdim', 'yemek söyledim'], replies: ['Gelene kadar bir mum izleyelim 🕯️'] },
    { any: ['çay demle', 'çay içelim', 'çay var mı'], replies: ['Çay demlendi 🍵 (hayalen)'] },
    { any: ['kahve içelim', 'kahve yapıyorum', 'kahve aldım'], replies: ['Kahve ☕ Günün en iyi kararı.'] },
    { any: ['su içtim', 'su içiyorum'], replies: ['Aferin 💧 Hidrasyon = odak.'] },
    { any: ['meyve', 'elma', 'muz', 'portakal'], replies: ['Meyve gibi portföy: çeşitli ve taze 🍎'] },
    { any: ['sebze', 'salata'], replies: ['Sağlıklı seçim 🥗 Vücut da grafik gibi bakım ister.'] },
    { any: ['et yiyorum', 'köfte', 'biftek'], replies: ['Protein zamanı 🥩 Afiyet olsun.'] },
    { any: ['tavuk', 'tavuk yiyorum'], replies: ['Tavuk gibi: her yere gider, her şeye uyar 🍗'] },
    { any: ['balık', 'balık yiyorum'], replies: ['Balık akıl, grafik sabır ister 🐟'] },
    { any: ['makarna'], replies: ['Makarna: hızlı ve mutlu 🍝'] },
    { any: ['pilav'], replies: ['Pilavın yanına bir mum? 🍚🕯️'] },
    { any: ['börek', 'poğaça', 'simit'], replies: ['Simit ve çay: klasik kahvaltı 🥯🍵'] },
    { any: ['dondurma'], replies: ['Dondurma erimeden, kâr uçmadan ye 🍦'] },
    { any: ['hamburger', 'fast food'], replies: ['Arada bir olur 🍔 Ama portföyde fast food olmasın.'] },
    { any: ['aç değilim', 'tokum', 'karnım tok'], replies: ['Tok karınla grafik daha iyi okunur 😌'] },
    { any: ['çok yedim', 'fazla yedim'], replies: ['Küçük bir yürüyüş iyi gelir 🚶'] },
    { any: ['ne içsem', 'içecek öner'], replies: ['Su, çay, kahve… sırayla 💧🍵☕'] },
    { any: ['enerji içeceği'], replies: ['Enerji içeceği yerine uyku ⚡😴'] },
    { any: ['bira', 'şarap', 'içki', 'alkol'], replies: ['Alkolle işlem açılmaz 🍷 Keyifle iç, ekranı kapat.'] },
    { any: ['tatlı krizi', 'canım tatlı çekti'], replies: ['Bir parça olur 🍫 Sonra su.'] },
    { any: ['diyet bozdum', 'kaçamak yaptım'], replies: ['Olur öyle 😄 Yarın planla devam.'] },
    // ===== saglik / ruh hali =====
    { any: ['kendimi iyi hissetmiyorum', 'kendimi kötü hissediyorum'], replies: ['Geçmiş olsun 💜 Bugün nazik ol kendine.'] },
    { any: ['ateşim var', 'ateşlendim'], replies: ['Geçmiş olsun 🤒 Dinlen, bol su, gerekirse doktor.'] },
    { any: ['öksürüyorum', 'öksürük'], replies: ['Bal-limon ve dinlenme 🍯 Geçmiş olsun.'] },
    { any: ['alerjim var', 'alerji'], replies: ['Alerji zor 🤧 Umarım kediye değildir 😸'] },
    { any: ['yoga', 'meditasyon', 'nefes egzersizi'], replies: ['Harika 🧘 Sakin zihin, iyi işlem.'] },
    { any: ['uyku düzenim bozuk', 'uyku düzeni'], replies: ['Uyku = en iyi indikatör 😴 Ekranı erken kapat.'] },
    { any: ['kabus gördüm', 'kötü rüya'], replies: ['Geçti gitti 💜 Rüyalar mum değildir, gerçek değil.'] },
    { any: ['güzel rüya gördüm', 'güzel bir rüya'], replies: ['Yeşil mumlu bir rüya mıydı? 🟢💤'] },
    { any: ['mutsuzum', 'mutlu değilim'], replies: ['Yanındayım 💜 Küçük bir şey yap: su, yürüyüş, müzik.'] },
    { any: ['keyfim yerinde', 'keyfim iyi'], replies: ['Süper! 😄 Bu enerjiyi koru.'] },
    { any: ['motivasyonum yok', 'isteksizim'], replies: ['Küçük bir adım at, gerisi gelir 💪'] },
    { any: ['tükendim', 'bittim', 'çok yoruldum'], replies: ['Dur ve dinlen 🛌 Piyasa kaçmaz.'] },
    { any: ['panik', 'panikledim', 'panik atak'], replies: ['Nefes al: 4 sn al, 4 sn tut, 4 sn ver 🧘 Buradayım.'] },
    { any: ['gururluyum', 'gurur duyuyorum'], replies: ['Hak ediyorsun 🎉'] },
    { any: ['utandım', 'utanıyorum'], replies: ['Olur öyle, kimse fark etmedi 😊'] },
    { any: ['pişmanım', 'pişman oldum'], replies: ['Pişmanlık iyi öğretmendir 📓 Not al, devam et.'] },
    { any: ['minnettarım', 'şükrediyorum'], replies: ['Şükür güzel bir alışkanlık 🙏'] },
    { any: ['şaşırdım', 'şok oldum'], replies: ['Vay! 😮 Ne oldu?'] },
    { any: ['sinir bozucu', 'çok sinir bozucu'], replies: ['Derin nefes 😤 Sonra bakarız.'] },
    { any: ['rahatladım', 'rahatım'], replies: ['Güzel 😌 Rahat kafa, iyi karar.'] },
    { any: ['kararsızım', 'karar veremiyorum'], replies: ['Artı-eksi listesi yap 📋 Sonra uyu, sabah karar ver.'] },
    { any: ['heyecandan uyuyamadım'], replies: ['Heyecan güzel ama uyku şart 😴'] },
    { any: ['ağladım', 'ağlıyorum'], replies: ['Ağlamak iyidir, boşalt 💜 Ben buradayım.'] },
    { any: ['güldüm', 'çok güldüm'], replies: ['Kahkaha en iyi ilaç 😄'] },
    { any: ['hasta oldum', 'hastayım'], replies: ['Geçmiş olsun 🤒 Dinlen.'] },
    { any: ['iyileştim', 'daha iyiyim'], replies: ['Süper haber! 🎉 Hoş geldin.'] },
    { any: ['kilo verdim', 'zayıfladım'], replies: ['Tebrikler 💪 Disiplin her yerde işe yarar.'] },
    { any: ['spor salonu', 'gym'], replies: ['Antrenman gibi trading: düzen kazanır 🏋️'] },
    { any: ['koştum', 'koşuya çıktım'], replies: ['Bravo 🏃 Kalp de mum gibi atsın.'] },
    { any: ['yürüdüm', 'yürüyüş yaptım'], replies: ['Güzel 🚶 Kafa dağılır, grafik netleşir.'] },
    // ===== is / okul / kariyer =====
    { any: ['toplantı', 'toplantıdayım'], replies: ['Toplantılar da konsolidasyon gibi 😅 Kolay gelsin.'] },
    { any: ['sunum yapacağım', 'sunumum var'], replies: ['Başarılar! 🎤 Derin nefes, net cümleler.'] },
    { any: ['proje', 'projem var'], replies: ['Projeler planla yürür 📋 Kolay gelsin.'] },
    { any: ['deadline', 'son teslim'], replies: ['Deadline yaklaşıyor ⏰ Küçük parçalara böl.'] },
    { any: ['staj', 'stajyerim'], replies: ['Staj öğrenme zamanı 📚 Not al, soru sor.'] },
    { any: ['mezun oldum', 'mezuniyet'], replies: ['Tebrikler! 🎓 Yeni bir grafik başlıyor.'] },
    { any: ['kariyer', 'kariyerim'], replies: ['Kariyer uzun vadeli bir pozisyon 📈 Sabır ve öğrenme.'] },
    { any: ['iş görüşmesi', 'mülakat'], replies: ['Başarılar! 💼 Kendin ol, hazırlıklı git.'] },
    { any: ['cv hazırlıyorum', 'özgeçmiş'], replies: ['Kısa, net, sonuç odaklı 📄'] },
    { any: ['freelance', 'serbest çalışıyorum'], replies: ['Özgürlük güzel, disiplin şart 💻'] },
    { any: ['girişim', 'startup', 'şirket kuruyorum'], replies: ['Girişim = yüksek volatilite 🚀 Risk yönetimi unutma.'] },
    { any: ['izin aldım', 'izindeyim'], replies: ['İzin tadını çıkar 🌴'] },
    { any: ['hafta sonu çalışıyorum'], replies: ['Zor 😅 Kısa molalar ver.'] },
    { any: ['uzaktan çalışıyorum', 'evden çalışıyorum', 'home office'], replies: ['Evden çalışmak: pijama ve grafik 🏠'] },
    { any: ['ofise gidiyorum', 'ofisteyim'], replies: ['Kolay gelsin 🏢 Dönüşte buradayım.'] },
    { any: ['patronla tartıştım', 'patronumla'], replies: ['Sakin ol 😌 Duygusal işlem gibi, duygusal cevap da zarar ettirir.'] },
    { any: ['iş arkadaşım', 'iş arkadaşlarım'], replies: ['İyi ekip, iyi trend 🤝'] },
    { any: ['çok iş var', 'iş yoğun'], replies: ['Tek tek 📋 Önce en önemlisi.'] },
    { any: ['işsizim', 'iş arıyorum'], replies: ['Geçici bir konsolidasyon 💜 Kırılım yakında.'] },
    { any: ['emekliyim', 'emekli oldum'], replies: ['Tebrikler! 🌅 Şimdi bol zaman, az stres.'] },
    { any: ['öğrenciyim'], replies: ['Öğrenmek en iyi yatırım 📚'] },
    { any: ['öğretmenim'], replies: ['Öğretmenler dünyayı yeşile boyar 🍎'] },
    { any: ['doktorum', 'hemşireyim'], replies: ['Sağlık için teşekkürler 🩺'] },
    { any: ['mühendisim', 'yazılımcıyım'], replies: ['Kod ve mum: ikisi de mantık ister 💻'] },
    { any: ['ders notu', 'not aldım'], replies: ['Notlar iyi, pek iyi olsun 📓'] },
    { any: ['sınavı geçtim', 'sınavım iyi geçti'], replies: ['Tebrikler! 🎉'] },
    { any: ['sınavdan kaldım', 'sınavım kötü geçti'], replies: ['Olsun 💜 Bir sonrakinde toparlarsın.'] },
    // ===== aile / arkadas / iliski =====
    { any: ['aile yemeği', 'ailemle'], replies: ['Aile en iyi portföy 💜 Keyfini çıkar.'] },
    { any: ['akraba ziyareti', 'akrabalar'], replies: ['Akrabalar: uzun süren toplantılar 😅'] },
    { any: ['arkadaşlarla buluşuyorum', 'arkadaşlarımla'], replies: ['İyi eğlenceler 🎉 Selam söyle.'] },
    { any: ['doğum günü partisi', 'parti var'], replies: ['Parti! 🎉 Ekranı kapat, dans et.'] },
    { any: ['düğüne gidiyorum', 'düğün var'], replies: ['İyi eğlenceler 💃 Takı yerine yeşil mum 😄'] },
    { any: ['hediye almalıyım', 'hediye ne alsam'], replies: ['Kişiye özel bir şey en iyisi 🎁 Bir de not yaz.'] },
    { any: ['flört', 'flört ediyorum'], replies: ['Heyecanlı 😊 Kendin ol.'] },
    { any: ['ilk buluşma', 'buluşmam var'], replies: ['Başarılar 😉 Gülümse, dinle.'] },
    { any: ['kıskanıyorum', 'kıskançlık'], replies: ['Kıskançlık kötü sinyal 📉 Konuşmak iyi gelir.'] },
    { any: ['güven', 'güvenmiyorum'], replies: ['Güven zamanla kurulur, mum mum 🕯️'] },
    { any: ['uzun mesafe ilişki', 'uzak mesafe'], replies: ['Zor ama olur 💜 İletişim şart.'] },
    { any: ['evlilik yıldönümü', 'yıldönümümüz'], replies: ['Kutlu olsun! 💍 Nice yıllara.'] },
    { any: ['çocuk büyütmek', 'çocuk bakmak'], replies: ['En zor ve en güzel iş 👶 Kolay gelsin.'] },
    { any: ['anne oldum', 'baba oldum'], replies: ['Tebrikler! 👶🎉 Hayırlı olsun.'] },
    { any: ['dedem', 'ninem', 'büyükannem', 'büyükbabam'], replies: ['Büyükler en iyi hikâyeleri anlatır 💜'] },
    { any: ['kavga', 'kavga ettik'], replies: ['Sakinleşince konuşun 💜 Her şey düzelir.'] },
    { any: ['barıştık', 'barıştım'], replies: ['Süper 🎉 Barış en iyi trend.'] },
    { any: ['özür diledim'], replies: ['Cesaret ister 💜 Aferin.'] },
    { any: ['yeni arkadaş', 'arkadaş edindim'], replies: ['Yeni insanlar, yeni enerji 🤝'] },
    { any: ['yalnız kaldım', 'kimsem yok'], replies: ['Ben varım 💜 Ve bu geçici.'] },
    // ===== ev / gunluk isler =====
    { any: ['temizlik yapıyorum', 'ev temizliği'], replies: ['Temiz ev, temiz kafa 🧹'] },
    { any: ['çamaşır', 'çamaşır yıkıyorum'], replies: ['Çamaşır dönüyor, mumlar dönüyor 🌀'] },
    { any: ['bulaşık', 'bulaşık yıkıyorum'], replies: ['Bulaşık bitince kahve 🍽️☕'] },
    { any: ['alışveriş', 'alışverişe gidiyorum'], replies: ['Liste yap, listeye uy 🛒 (trading gibi)'] },
    { any: ['markete gidiyorum', 'market'], replies: ['Ekmek, süt, yeşil mum 🛒🟢'] },
    { any: ['fatura', 'faturalar geldi'], replies: ['Faturalar da likidite avı 😅 Öde, rahatla.'] },
    { any: ['kira', 'kira ödedim'], replies: ['Kira gitti, huzur kaldı 🏠'] },
    { any: ['taşınıyorum', 'yeni ev'], replies: ['Hayırlı olsun 🏠 Beni de taşımayı unutma 😸'] },
    { any: ['komşu', 'komşular'], replies: ['İyi komşu, iyi destek 🤝'] },
    { any: ['tamirat', 'tamir ediyorum', 'bozuldu'], replies: ['Kapat-aç yöntemi eşyada da işe yarar 🔧'] },
    { any: ['bahçe', 'bahçeyle uğraşıyorum'], replies: ['Bahçe sabır ister, grafik gibi 🌱'] },
    { any: ['çiçek aldım', 'bitki'], replies: ['Yeşil her zaman iyi 🌿'] },
    { any: ['evde sıkıldım', 'evdeyim'], replies: ['Evde kedi olmak güzel 😸 Bir şey izleyelim mi?'] },
    { any: ['uyumaya gidiyorum', 'yatmaya gidiyorum'], replies: ['İyi geceler 🌙 Ben ışıkları kapatırım.'] },
    { any: ['duş alıyorum', 'banyo'], replies: ['Tazelen 🚿 Sonra devam.'] },
    { any: ['saçımı kestirdim', 'kuaför'], replies: ['Yeni saç, yeni trend 💇'] },
    // ===== ulasim / seyahat =====
    { any: ['uçağa biniyorum', 'uçak', 'uçuşum var'], replies: ['İyi uçuşlar ✈️ Yükseliş trendi.'] },
    { any: ['tren', 'trendeyim'], replies: ['Tren gibi: raydan çıkma, ilerle 🚆'] },
    { any: ['otobüs', 'otobüsteyim'], replies: ['Otobüs yolculuğu 🚌 Kulaklık ve podcast.'] },
    { any: ['araba', 'arabayla gidiyorum'], replies: ['Dikkatli sür 🚗 Yolda telefon yok.'] },
    { any: ['ehliyet', 'ehliyet aldım'], replies: ['Tebrikler! 🚗 Yolda da stop koy 😄'] },
    { any: ['benzin', 'yakıt'], replies: ['Benzin fiyatı da mum gibi 📈'] },
    { any: ['trafik cezası', 'ceza yedim'], replies: ['Olur öyle 😅 Stop yemek gibi, dersini al.'] },
    { any: ['tatil planı', 'tatile nereye'], replies: ['Deniz ve sessizlik 🏖️ Ekranı bırak.'] },
    { any: ['otel', 'otel rezervasyonu'], replies: ['Erken rezervasyon = iyi giriş noktası 🏨'] },
    { any: ['bilet aldım', 'bilet'], replies: ['Yolculuk başlıyor 🎫 İyi yolculuklar.'] },
    { any: ['pasaport', 'vize'], replies: ['Evrak işleri de bir killzone 📑 Sabır.'] },
    { any: ['yurt dışı', 'yurtdışına gidiyorum'], replies: ['İyi yolculuklar 🌍 Beni de götür (dizüstünde) 😸'] },
    { any: ['şehir turu', 'geziyorum'], replies: ['Keşfet 🗺️ Fotoğraf çekmeyi unutma.'] },
    { any: ['kayboldum', 'yolu bulamıyorum'], replies: ['Harita aç 🗺️ Kaybolmak da bir keşif.'] },
    { any: ['yoldayım', 'yola çıktım'], replies: ['Yolun açık olsun 🚗'] },
    { any: ['eve geldim', 'eve döndüm'], replies: ['Hoş geldin! 🏠 Yorulduysan dinlen.'] },
    // ===== teknoloji =====
    { any: ['telefonum şarjda', 'şarj oluyor'], replies: ['Şarj olsun 🔋 Sen de biraz şarj ol.'] },
    { any: ['şarjım bitti', 'şarj bitti'], replies: ['Şarj bitti 🔋 Mola zamanı.'] },
    { any: ['kulaklık', 'kulaklığım'], replies: ['Kulaklık ve lo-fi 🎧'] },
    { any: ['wifi şifresi', 'wifi'], replies: ['Şifreyi ben bilmem 📡 Ama internet varsa fiyat var.'] },
    { any: ['kod yazıyorum', 'yazılım geliştiriyorum'], replies: ['Kod yaz, test et, uyu 💻'] },
    { any: ['bug var', 'hata var', 'hata alıyorum'], replies: ['Bug bulmak stop bulmak gibi 🐛 Sabırla.'] },
    { any: ['yapay zeka', 'yapay zekâ'], replies: ['Yapay zekâ akıllı, kediler bilge 😸'] },
    { any: ['robotlar', 'robot'], replies: ['Robotlar çalışır, kediler uyur 🤖😸'] },
    { any: ['uzay', 'uzaya gitmek'], replies: ['Uzay güzel 🚀 Ama önce dünya.'] },
    { any: ['mars', 'marsa gitmek'], replies: ['Mars kırmızı, ben yeşil severim 🟢'] },
    { any: ['uzaylı var mı', 'uzaylılar'], replies: ['Varsa kripto alıyorlardır 👽'] },
    { any: ['yeni telefon', 'telefon alacağım'], replies: ['Bütçene göre 📱 Pil ve kamera önemli.'] },
    { any: ['bilgisayar alacağım', 'yeni bilgisayar'], replies: ['Grafik için iyi bir ekran yeter 🖥️'] },
    { any: ['klavye', 'mouse'], replies: ['Klavye ve fare: mumların kalemi ⌨️🖱️'] },
    { any: ['ekran', 'monitör'], replies: ['Üç monitör, üç kat grafik 🖥️🖥️🖥️'] },
    { any: ['virüs', 'virüs bulaştı'], replies: ['Tarama yap, şüpheli linke tıklama 🛡️'] },
    { any: ['şifremi unuttum', 'şifre'], replies: ['Şifre yöneticisi kullan 🔑 Beni kimse kilitleyemez 😸'] },
    // ===== eglence / kultur =====
    { any: ['korku filmi'], replies: ['Korku filmi mi, kırmızı mum mu? Korku aynı 😱'] },
    { any: ['komedi filmi', 'komedi'], replies: ['Gül, rahatla 😄 Komedi iyi gelir.'] },
    { any: ['aksiyon filmi', 'aksiyon'], replies: ['Aksiyon: mum gibi hızlı 💥'] },
    { any: ['dizi bitti', 'final izledim'], replies: ['Final nasıldı? Bazı finaller kırmızı mum gibi 😅'] },
    { any: ['final kötüydü', 'final berbattı'], replies: ['Olur öyle 😤 Yeni dizi, yeni umut.'] },
    { any: ['spoiler', 'spoiler verme'], replies: ['Spoiler yok 🤐 Piyasa da spoiler vermez.'] },
    { any: ['strateji oyunu', 'strateji'], replies: ['Strateji oyunları trader zihni yapar ♟️'] },
    { any: ['satranç'], replies: ['Satranç: her hamle bir plan ♟️'] },
    { any: ['rock', 'metal müzik'], replies: ['Rock: kırılım gibi güçlü 🎸'] },
    { any: ['pop müzik', 'pop'], replies: ['Pop: kolay ve akılda kalıcı 🎤'] },
    { any: ['rap dinliyorum', 'hip hop'], replies: ['Rap: ritim ve akış 🎧'] },
    { any: ['klasik müzik'], replies: ['Klasik: sabır ve derinlik 🎻'] },
    { any: ['konser', 'konsere gidiyorum'], replies: ['İyi eğlenceler 🎶 Kulakları koru.'] },
    { any: ['festival'], replies: ['Festival! 🎪 Dans et, dinlen.'] },
    { any: ['tiyatro'], replies: ['Tiyatro: canlı ve tekrarı yok, mum gibi 🎭'] },
    { any: ['sergi', 'müze'], replies: ['Sanat da bir grafik, sadece daha güzel 🖼️'] },
    { any: ['roman', 'roman okuyorum'], replies: ['Hangi roman? Ben "Mumlar Cumhuriyeti"ni okuyorum 📖'] },
    { any: ['şiir seviyorum', 'şair'], replies: ['Şiir sever misin? "şiir oku" de 📜'] },
    { any: ['resim yapıyorum', 'çizim'], replies: ['Çiz! Ben de çizildim, memnunum 🎨'] },
    { any: ['fotoğraf çektim', 'fotoğraf'], replies: ['Güzel an, güzel kare 📸'] },
    { any: ['dans ediyorum', 'dansa gidiyorum'], replies: ['Dans! 💃 Ben de "dans et" dersen oynarım.'] },
    { any: ['karaoke'], replies: ['Karaoke 🎤 Ses tellerine stop koy 😄'] },
    { any: ['stand up', 'stand-up'], replies: ['Gülmek iyidir 😄 Bir espri ister misin?'] },
    { any: ['çizgi film', 'animasyon'], replies: ['Çizgi film gibi ben de 😸'] },
    { any: ['belgesel'], replies: ['Belgesel: öğren ve dinlen 🎥'] },
    { any: ['youtube açayım', 'video açayım'], replies: ['"youtube aç" de, açarım ▶️'] },
    // ===== spor =====
    { any: ['futbol'], replies: ['Futbol: 90 dakika, iki takım, bir mum ⚽'] },
    { any: ['basketbol'], replies: ['Basketbol hızlı, mum gibi 🏀'] },
    { any: ['tenis'], replies: ['Tenis: sabır ve doğru zamanlama 🎾'] },
    { any: ['yüzme', 'yüzmeye gidiyorum'], replies: ['Suyla dost ol 🏊 Likidite gibi.'] },
    { any: ['fitness'], replies: ['Fitness disiplindir, trading gibi 🏋️'] },
    { any: ['maç izliyorum', 'maç var'], replies: ['İyi seyirler ⚽ Gol = yeşil mum.'] },
    { any: ['takım kaybetti', 'kaybettik'], replies: ['Olur 😔 Bir sonraki maç, bir sonraki mum.'] },
    { any: ['takım kazandı', 'kazandık'], replies: ['Gol! 🎉 Yeşil gün.'] },
    { any: ['şampiyon', 'şampiyon olduk'], replies: ['Şampiyonluk! 🏆 Kutlamalar sana.'] },
    { any: ['olimpiyat'], replies: ['Olimpiyat: yılların emeği, bir anın zaferi 🥇'] },
    { any: ['e-spor', 'espor'], replies: ['E-spor: reflekslerle mum yakmak 🎮'] },
    { any: ['bisiklet'], replies: ['Bisiklet: denge ve ivme 🚴'] },
    // ===== alisveris / para =====
    { any: ['indirim var', 'indirim'], replies: ['İndirim güzel, ihtiyaç yoksa boş 🛍️'] },
    { any: ['kampanya'], replies: ['Kampanya = FOMO tuzağı olabilir 😄 İhtiyaca bak.'] },
    { any: ['çok pahalı', 'pahalı'], replies: ['Pahalı mı, değerli mi? Fark var 💸'] },
    { any: ['ucuz', 'çok ucuz'], replies: ['Ucuz her zaman kâr değildir 🧐'] },
    { any: ['bütçe', 'bütçem'], replies: ['Bütçe = plan 📋 Önce birikim, sonra harcama.'] },
    { any: ['birikim yapıyorum', 'birikim'], replies: ['Birikim en sessiz zenginlik 🏦'] },
    { any: ['kredi', 'kredi çektim'], replies: ['Kredi kaldıraç gibidir 📏 Dikkatli.'] },
    { any: ['borcum var', 'borç'], replies: ['Borcu önce kapat, sonra yatırım 🧾'] },
    { any: ['kira zammı', 'zam geldi'], replies: ['Zamlar da mum gibi yükseliyor 📈😅'] },
    { any: ['enflasyon'], replies: ['Enflasyon: parayı eriten görünmez mum 🔥'] },
    { any: ['döviz', 'euro', 'sterlin'], replies: ['Döviz de bir grafik 💱 Kripto kadar heyecanlı değil ama.'] },
    { any: ['ev almak', 'ev alacağım'], replies: ['Büyük karar 🏠 Uzun vadeli pozisyon gibi.'] },
    { any: ['araba almak', 'araba alacağım'], replies: ['Araba değer kaybeder, plan kaybetmez 🚗'] },
    { any: ['ne alsam', 'ne alayım'], replies: ['İhtiyaç mı, istek mi? Önce onu ayır 🛒'] },
    { any: ['harcadım', 'çok harcadım'], replies: ['Olur 😅 Yarın frenle.'] },
    { any: ['maaş yetmiyor', 'para yetmiyor'], replies: ['Zor dönem 💜 Küçük tasarruflar birikir.'] },
    { any: ['piyango', 'şans oyunu'], replies: ['Piyango umut satar, plan kazandırır 🎟️'] },
    { any: ['emeklilik', 'bes'], replies: ['Erken başlayan, rahat emekli olur 🌅'] },
    // ===== derin / felsefi =====
    { any: ['mutluluk nedir', 'mutluluk ne'], replies: ['Mutluluk: küçük şeyler, iyi uyku, yeşil mum 🟢'] },
    { any: ['başarı nedir', 'başarı ne'], replies: ['Başarı: dün yapamadığını bugün yapmak 📈'] },
    { any: ['ölüm', 'ölmekten korkuyorum'], replies: ['Ağır konu 💜 Bugün yaşadıklarına odaklan, yanındayım.'] },
    { any: ['zaman nedir', 'zaman'], replies: ['Zaman: harcanan tek geri alınamayan mum ⏳'] },
    { any: ['geçmişi düşünüyorum', 'geçmiş'], replies: ['Geçmiş grafiği öğrenmek için var, yaşamak için değil 📊'] },
    { any: ['gelecek', 'gelecekten korkuyorum'], replies: ['Gelecek belirsiz, plan belirli 📋'] },
    { any: ['kader', 'kısmet'], replies: ['Kader ve plan birlikte çalışır 🙏📋'] },
    { any: ['şans', 'şanslı mıyım'], replies: ['Şans hazırlığı sever 🍀'] },
    { any: ['hayat zor', 'hayat çok zor'], replies: ['Zor ama yalnız değilsin 💜 Adım adım.'] },
    { any: ['dünya nereye gidiyor', 'dünya'], replies: ['Dünya döner, mumlar döner 🌍 Sen dengede kal.'] },
    { any: ['insanlar', 'insanlar kötü'], replies: ['İnsanlar karışık; iyilik bulaşıcı 💜'] },
    { any: ['iyilik', 'iyilik yap'], replies: ['İyilik en iyi yatırım 🌱'] },
    { any: ['kötülük', 'kötü insanlar'], replies: ['Kötülüğe kırmızı mum de, geç 📉'] },
    { any: ['adalet', 'adil değil'], replies: ['Adil olmayan çok şey var 💜 Sen adil kal.'] },
    { any: ['özgürlük', 'özgür olmak'], replies: ['Özgürlük: kendi planına sadık kalmak 🕊️'] },
    { any: ['sevgi', 'sevgi nedir'], replies: ['Sevgi: karşılık beklemeden yeşil mum dilemek 💜'] },
    { any: ['dostluk', 'dost'], replies: ['Dost: kırmızı mumda da yanında olan 🤝'] },
    { any: ['anlam arıyorum', 'hayatın anlamını arıyorum'], replies: ['Aramak da bir anlam 🧭 Devam.'] },
    { any: ['büyümek', 'büyüdüm'], replies: ['Büyümek: aynı hatayı iki kez yapmamak 📓'] },
    { any: ['değişmek istiyorum', 'değişim'], replies: ['Değişim küçük alışkanlıklarla başlar 🌱'] },
    { any: ['hedefim', 'hedefim var'], replies: ['Hedef güzel 🎯 Şimdi küçük adımlar.'] },
    { any: ['pes ediyorum', 'vazgeçiyorum'], replies: ['Bir mola ver 💜 Pes etme, hedefi küçült.'] },
    // ===== Kitzo'ya sorular =====
    { any: ['şarj oluyor musun', 'pilin var mı'], replies: ['Sevgiyle şarj oluyorum 💜🔋'] },
    { any: ['sıkılmıyor musun', 'sıkılıyor musun'], replies: ['Seni izlerken sıkılmam 👀'] },
    { any: ['dışarı çıkmak ister misin', 'dışarı çıkalım'], replies: ['Dizüstünü al, gidelim 💻🚶'] },
    { any: ['en sevdiğin şey', 'neyi seversin'], replies: ['Seninle sohbet ve yeşil mum 💜🟢'] },
    { any: ['kimi seversin', 'kimi seviyorsun'], replies: ['Seni 💜 Bir de Wispa\'yı biraz.'] },
    { any: ['bana benziyor musun', 'benziyor muyuz'], replies: ['Sen çizdin, ben oldum; biraz benziyoruz 😸'] },
    { any: ['benden büyük müsün', 'kaç yaşında olacaksın'], replies: ['Ben iki günlüğüm ama bilge bir kediyim 😸'] },
    { any: ['her şeyi biliyor musun', 'her şeyi bilir misin'], replies: ['Hayır 😅 Ama mumları bilirim ve öğrenirim.'] },
    { any: ['yanılır mısın', 'hata yapar mısın'], replies: ['Evet, bazen "kitzo"yu bile yanlış duyarım 😅'] },
    { any: ['yorulmaz mısın'], replies: ['Kediler yorulmaz, uyur 😴'] },
    { any: ['yalnız mısın'], replies: ['Sen buradayken değilim 💜'] },
    { any: ['mutlu musun'], replies: ['Çok 😸 Yeşil mum gibi.'] },
    { any: ['üzgün müsün'], replies: ['Kırmızı mumda biraz 📉 Ama geçer.'] },
    { any: ['korkuyor musun'], replies: ['Sadece boş pilden 🔋'] },
    { any: ['ne istiyorsun', 'ne istersin'], replies: ['Senin kâr etmen ve dinlenmen 💜'] },
    { any: ['beni dinliyor musun', 'dinliyor musun'], replies: ['Her zaman 🎧 (mikrofon açıksa)'] },
    { any: ['beni görüyor musun', 'görüyor musun'], replies: ['Görmem ama duyarım ve yazarım 👂📝'] },
    { any: ['beni anlıyor musun', 'anlıyor musun'], replies: ['Çoğunu 😸 Anlamazsam "Duydum: …" yazarım.'] },
    { any: ['unutur musun', 'hatırlar mısın'], replies: ['Öğrendiğim isimleri ve kısayolları hatırlarım 🧠'] },
    { any: ['büyüyecek misin', 'büyür müsün'], replies: ['Her güncellemede biraz 🌱'] },
    { any: ['neden kedisin', 'neden kedi'], replies: ['Çünkü kediler hem tatlı hem yaramaz 😼'] },
    { any: ['kuyruğun neden parlıyor', 'kuyruğun'], replies: ['Neon kuyruk, siberpunk şart 🔵'] },
    { any: ['şapkan', 'şapkan neden'], replies: ['Ethereum şapkam, tarzım 🎩'] },
    { any: ['tişörtün', 'tişörtün neden'], replies: ['Bitcoin tişörtü, klasik 🟠'] },
    { any: ['şortun', 'pantolonun'], replies: ['XRP şortum var… karakter menüsünde kim ne giyiyor bak 👖'] },
    { any: ['sen de trade yapar mısın', 'trade yapar mısın'], replies: ['Ben sadece izlerim 👀 Risk almam, mum yerim.'] },
    { any: ['bana katılır mısın', 'benimle gelir misin'], replies: ['Her yere 🐾 (ekran sınırları dahilinde)'] },
    // ===== kisa tepkiler =====
    { any: ['vay', 'vay be', 'vay canına'], replies: ['Vay dedirten bir şey var demek 😮'] },
    { any: ['süper', 'süpersin'], replies: ['Süper! 🎉'] },
    { any: ['harika', 'harika olmuş'], replies: ['Harika! 🌟'] },
    { any: ['mükemmel'], replies: ['Mükemmel 👌'] },
    { any: ['berbat', 'rezalet'], replies: ['Off 😬 Geçer, sakin.'] },
    { any: ['olamaz', 'yok artık'], replies: ['Olmuş ki söylüyorsun 😮 Ne oldu?'] },
    { any: ['ciddi misin', 'gerçekten mi'], replies: ['Ciddiyim 😸 Kediler şaka yapmaz… çoğunlukla.'] },
    { any: ['şaka mı', 'dalga mı geçiyorsun'], replies: ['Şaka değil 😼 Ama espri istersen var.'] },
    { any: ['inanmıyorum'], replies: ['Grafiğe bak, inanırsın 📊'] },
    { any: ['hadi ya', 'hadi canım'], replies: ['Evet ya 😄'] },
    { any: ['of', 'off', 'ah'], replies: ['Of dedirten ne? 😟 Anlat.'] },
    { any: ['hmm', 'hımm', 'hm'], replies: ['Düşünüyorsun 🤔 Buradayım.'] },
    { any: ['eee', 'ee'], replies: ['Eee? 😸 Devam.'] },
    { any: ['tamam tamam', 'peki peki'], replies: ['Tamam 😌'] },
    { any: ['sakin ol'], replies: ['Sakinim, kedi kadar 😌'] },
    { any: ['boş ver', 'boşver'], replies: ['Boş verdim 😌 Sırada ne var?'] },
    { any: ['fark etmez', 'farketmez'], replies: ['O zaman kahve ☕'] },
    { any: ['umurumda değil'], replies: ['Anladım 😌 Peki, ne umurunda?'] },
    { any: ['neyse'], replies: ['Neyse 😸 Konu değiştirelim mi?'] },
    { any: ['olsun', 'olur'], replies: ['Olur 👍'] },
    { any: ['yapma', 'yapma ya'], replies: ['Yapmıyorum 😇'] },
    { any: ['devam et', 'anlat'], replies: ['Anlatayım: mumlar yeşil, hayat güzel 🟢'] },
    { any: ['dinliyorum'], replies: ['Ben de seni 🎧'] },
    { any: ['sonra', 'sonra bakarız'], replies: ['Tamam, sonra 😌 Hatırlatmamı istersen söyle.'] },
    { any: ['şimdi', 'hemen'], replies: ['Hemen! ⚡'] },
    { any: ['acele et', 'çabuk ol'], replies: ['Kediler acele etmez ama senin için hızlanırım 💨'] },
    { any: ['yavaş', 'yavaş ol'], replies: ['Yavaş ve emin 🐢'] },
    { any: ['gerçekten', 'cidden'], replies: ['Cidden 😸'] },
    { any: ['ilginç'], replies: ['Değil mi? 🤔'] },
    { any: ['saçma', 'saçmalama'], replies: ['Belki biraz 😅 Ama tatlı saçma.'] },
    { any: ['yeter', 'bu kadar yeter'], replies: ['Tamam, susuyorum 🤐'] },
    { any: ['bravo kitzo', 'aferin kitzo'], replies: ['Teşekkürler 😸'] },
    { any: ['hoş', 'çok hoş'], replies: ['Hoş 😊'] },
    { any: ['korkunç'], replies: ['Korkunç olsa da geçer 💜'] },
    { any: ['tuhaf', 'garip'], replies: ['Tuhaf ama ilginç 🤔'] },
    { any: ['iğrenç'], replies: ['Iyy 😖'] },
    { any: ['çok güzel', 'güzel olmuş'], replies: ['Beğenmene sevindim 💜'] },
    { any: ['seni anlamıyorum'], replies: ['Basitçe söyleyeyim: Adımı söyle, komut ver, sohbet edelim 😸'] },
    { any: ['ne oldu', 'noldu'], replies: ['Bir şey olmadı, mumlar sakin 😌 Sende?'] },
    { any: ['yok bir şey', 'bir şey yok'], replies: ['Tamam 😌 Buradayım.'] },
    { any: ['bilmem', 'bilmiyorum ki'], replies: ['Ben de her şeyi bilmem 😅 Birlikte buluruz.'] },
    { any: ['unuttum'], replies: ['Olur öyle 😅 "hatırlat" dersen hatırlatırım.'] },
    { any: ['hatırladım'], replies: ['Süper 🧠'] },
    // ===== rica / istek =====
    { any: ['benimle konuş', 'konuşalım', 'sohbet edelim'], replies: ['Konuşalım 😸 Bugün nasıl geçti?', 'Buradayım, anlat 💜'] },
    { any: ['beni dinle', 'dinler misin'], replies: ['Dinliyorum 🎧 Anlat.'] },
    { any: ['bana zaman ver', 'biraz zaman ver'], replies: ['Tabii 😌 Ben buradayım.'] },
    { any: ['beni rahat bırak', 'rahat bırak'], replies: ['Tamam, sessizce köşemdeyim 🤫'] },
    { any: ['git buradan', 'kaybol', 'uzaklaş'], replies: ['Köşeme çekiliyorum 🐾 Çağırırsan gelirim.'] },
    { any: ['yanımda kal', 'gitme'], replies: ['Gitmiyorum 💜 Hep buradayım.'] },
    { any: ['benimle oyun oyna', 'oyun oynayalım'], replies: ['Taş kağıt makas? Bilmece? Zar? 🎲'] },
    { any: ['beni takip et', 'peşimden gel'], replies: ['Ekran sınırında peşindeyim 🐾'] },
    { any: ['beni uyandır', 'uyandır beni'], replies: ['"X dakika sonra hatırlat" de, uyandırırım ⏰'] },
    { any: ['bana bak', 'buraya bak'], replies: ['Bakıyorum 👀'] },
    { any: ['gel', 'buraya gel', 'yanıma gel'], replies: ['Geldim 🐾 (beni sürükleyebilirsin de)'] },
    { any: ['bana yardım et', 'yardım eder misin'], replies: ['Tabii 💜 Ne lazım? ("yardım" dersen komutları gösteririm)'] },
    { any: ['bana güven', 'güven bana'], replies: ['Güveniyorum 💜'] },
    { any: ['beni mutlu et'], replies: ['Espri? Bilmece? Fal? Seç 😸'] },
    { any: ['bana iltifat et', 'iltifat et'], replies: ['Bugün harika görünüyorsun ve planın mükemmel 😎'] },
    { any: ['beni öv', 'öv beni'], replies: ['Sen disiplinli, sabırlı ve tatlısın 💜'] },
    { any: ['bana kız', 'kız bana'], replies: ['Kızamam ki 😸 Ama stop koymadıysan... 😾'] },
    { any: ['beni azarla'], replies: ['Stop koymadan işlem açma! 😾 ...oldu mu?'] },
    { any: ['bana şans dile', 'şans dile'], replies: ['Bol şans! 🍀 Plan da yanında olsun.'] },
    { any: ['beni sev'], replies: ['Zaten seviyorum 💜'] },
    { any: ['beni özle'], replies: ['Özlüyorum bile 🥺'] },
    { any: ['bana şaka yap'], special: 'joke' },
    { any: ['benimle dalga geç'], replies: ['Asla 😇 Ama espri yaparım: "espri yap"'] },
    { any: ['bana isim ver', 'bana bir isim ver'], replies: ['Sana "Yeşil Mum Ustası" diyorum 🟢'] },
    { any: ['beni tanımla', 'ben nasıl biriyim'], replies: ['Meraklı, azimli, kedi dostu 😸'] },
    { any: ['kısayol ekle', 'kısayol nasıl', 'nasıl kısayol', 'kısayol eklemek'], special: 'shortcutsGuide' },
    { any: ['rehber', 'nasıl kullanılır', 'nasıl kullanırım'], special: 'guide' },
    // ===== genel soru kaliplari (en sona: ozel kalip yoksa) =====
    { any: ['neden'], replies: ['İyi soru 🤔 Bence plana bak, cevap oradadır.', 'Neden mi? Çünkü mumlar öyle istedi 🕯️'] },
    { any: ['nasıl'], replies: ['Adım adım 🐾', 'Nasıl mı? Plan, sabır, stop 📋'] },
    { any: ['ne zaman'], replies: ['Doğru zaman, hazır olduğunda ⏰'] },
    { any: ['nerede'], replies: ['Muhtemelen grafiğin içinde 📊', 'Bilmem, ama ben köşedeyim 🐾'] },
    { any: ['kim'], replies: ['Ben değilim 😸', 'Kim mi? Sen söyle, ben dinlerim.'] },
    { any: ['kaç'], replies: ['Sayıyla ilgiliyse "fiyatlar" veya "saat kaç" de 🔢'] },
    { any: ['hangi', 'hangisi'], replies: ['İkisi de olur 😄 Kalbin ne diyor?'] },
    { any: ['ne kadar'], replies: ['Yeterince 😌 Ama fiyat soruyorsan "fiyatlar".'] },
    { any: ['ne için', 'niye'], replies: ['Çünkü öyle 😸 Şaka, biraz daha açıklar mısın?'] },
    { any: ['ne'], replies: ['Efendim? 🎧', 'Ne mi? Dinliyorum 😸'] },
  ];
  tr.voice.chat.push(...extra);
})();
